# Site settings
title: Niclas Boklund
email: nb222ei@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Course “1DV022 – Client-based Webprogramming” at Linnaeus university.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  nibo1994

# Build settings
markdown: kramdown
